# Nome da aplicação
spring.application.name=fin-control-api

# Configuração do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/fincontrol
spring.datasource.username=postgres
spring.datasource.password=postgres

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect